---

- name: Destroy BIG-IP instance
  hosts: engine
  gather_facts: false
  tasks:
  - name: remove an instance
    os_server:
      name: "client-{{ item }}"
      state: absent
    with_items: "{{ client_node_id }}"
