---
- name: Assign license to BIG-IP
  hosts: f5
  gather_facts: false
  vars:
    bigip_password: "Dimensiondata555"
  tasks:
  - name: assign license
    uri:
      url: "https://{{inventory_hostname}}/mgmt/shared/declarative-onboarding"
      method: POST
      user: admin
      password: "{{bigip_password}}"
      force_basic_auth: true
      validate_certs: no
      headers:
        Origin: "https://{{inventory_hostname}}"
        Content-Type: application/json;charset=UTF-8
      body: "{{ lookup('file','license.json') | to_json }}"
      body_format: json
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
