---
- name: BIG-IP on boarding
  hosts: engine
  gather_facts: false
  vars:
    provider:
      user: admin
      validate_certs: no
      server_port: 443
    bigip_password: "Dimensiondata555"

  tasks:
  - name: configure admin password
    uri:
      url: "https://172.16.121.{{ item }}/mgmt/shared/authz/users/admin"
      method: PATCH
      body: "{\"oldPassword\":\"admin\",\"password\":\"{{ bigip_password }}\"}"
      body_format: json
      validate_certs: no
      force_basic_auth: yes
      user: admin
      password: admin
      headers:
        Content-Type: "application/json"
      state: present
    with_items: "{{ node_id }}"
    ignore_errors: yes


  - name: configure root password
    bigip_user:
      username_credential: root
      password_credential: "{{ bigip_password }}"
      update_password: always
      provider: "{{ provider }}"
      server: "172.16.121.{{ item }}"
      password: "{{ bigip_password }}"
      state: present
    with_items: "{{ node_id }}"
