---
- name: BIG-IP Signal VNF provisioning
  hosts: engine
  gather_facts: false
  vars:
    provider:
      user: admin
      validate_certs: no
      server_port: 443
      password: "Dimensiondata555"
    default_password: "password"
    bigip_password: "Dimensiondata555"


  tasks:

  - name: Create static route with gateway address
    bigip_management_route:
      network: 172.16.0.0/16
      gateway: 172.16.121.1
      name: mgmt-route
      provider: "{{ provider }}"
      server: "172.16.121.{{ item }}"
    with_items: "{{ db_node_id }}"

  - name: Create static route with gateway address
    bigip_static_route:
      destination: 0.0.0.0
      netmask: 0.0.0.0
      gateway_address: 172.16.103.253
      name: default
      provider: "{{ provider }}"
      server: "172.16.121.{{ item }}"
    with_items: "{{ db_node_id }}"
